
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  password: qwerty
  pool: 5
  host: localhost

development:
  <<: *default
  database: user_app_development

test:
  <<: *default
  database: user_app_test

production:
  <<: *default
  database: user_app_production
  username: user_app
  password: <%= ENV['USER_APP_DATABASE_PASSWORD'] %>
